twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme:
        - 'shared/form.html.twig'
    globals:
        project: '@App\Project'
        menu: '@App\Extension\RBAC\Menu'

when@test:
    twig:
        strict_variables: true
